module.exports = {
  apps: [{
    name: 'pnptv-bot',
    script: './src/bot/core/bot.js',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    node_args: '--dns-result-order=ipv4first',
    exec_mode: 'fork',
    cwd: '/root/pnptvbot-production',
    env: {
      NODE_ENV: 'production',
      PORT: '3001',
      NODE_OPTIONS: '--dns-result-order=ipv4first',
      BOT_LOCK_ENABLED: 'false',
      POSTGRES_HOST: 'localhost',
      POSTGRES_PORT: '5432',
      POSTGRES_DATABASE: 'pnptvbot',
      POSTGRES_USER: 'pnptvbot',
      POSTGRES_PASSWORD: 'Apelo801050#',
      SESSION_SECRET: '32c1d6331348d5fc1f7a4a4809e1fe5d3361a02eadd55d57338cb9b7b8842365',
      WEBAPP_X_CLIENT_ID: 'SGwwVTZNNV9WUnQyZkh1RVFoVlk6MTpjaQ',
      WEBAPP_X_CLIENT_SECRET: 'kAdNTI36RFFj81wHc6Z_H-g2Q5wNNSC--bL2cwpiFnSZ8GIswg',
      WEBAPP_X_REDIRECT_URI: 'https://pnptv.app/api/webapp/auth/x/callback',
    },
    env_production: {
      NODE_ENV: 'production',
      PORT: '3001',
      NODE_OPTIONS: '--dns-result-order=ipv4first',
      BOT_LOCK_ENABLED: 'false',
      POSTGRES_HOST: 'localhost',
      POSTGRES_PORT: '5432',
      POSTGRES_DATABASE: 'pnptvbot',
      POSTGRES_USER: 'pnptvbot',
      POSTGRES_PASSWORD: 'Apelo801050#',
      SESSION_SECRET: '32c1d6331348d5fc1f7a4a4809e1fe5d3361a02eadd55d57338cb9b7b8842365',
      WEBAPP_X_CLIENT_ID: 'SGwwVTZNNV9WUnQyZkh1RVFoVlk6MTpjaQ',
      WEBAPP_X_CLIENT_SECRET: 'kAdNTI36RFFj81wHc6Z_H-g2Q5wNNSC--bL2cwpiFnSZ8GIswg',
      WEBAPP_X_REDIRECT_URI: 'https://pnptv.app/api/webapp/auth/x/callback',
    },
    env_development: {
      NODE_ENV: 'development',
    },
    error_file: './logs/pm2-error.log',
    out_file: './logs/pm2-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    min_uptime: '10s',
    max_restarts: 10,
    restart_delay: 4000,
    kill_timeout: 5000,
    wait_ready: false,
    listen_timeout: 10000,
    ignore_watch: ['node_modules', 'logs'],
  }],
};
